// =============================================================================
//  THE LAUNDRY BAG, content source of truth for the new site.
//
//  PRIMARY  , verbatim copy from the existing/legacy thelaundrybag.co.in site.
//  RESEARCHED, facts gathered from public sources (LinkedIn, JustDial,
//               Play Store, press) and cross-referenced with the owner's
//               details. Clearly separated so it can be reviewed/edited.
// =============================================================================

// ----- PRIMARY ---------------------------------------------------------------

export const site = {
  name: "The Laundry Bag",
  shortName: "TLB",
  legalName: "The Laundry Bag™",
  tagline: "Commercial Laundry, Dry Cleaning & Linen Management",
  taglinePrimary: "India's Leading Laundry Service Provider",
  promise: "Wash · Dry · Finish",
  motto: "India's Leading Laundry Service Provider",
  description:
    "The Laundry Bag is one of India's leading commercial laundry, dry cleaning and linen management brands, founded by Shourya Jain in Raipur, Chhattisgarh in 2013. From our Raipur headquarters and central processing unit we run on-premise laundry units, off-site processing and linen rental services for luxury hotels, resorts, hospitals and institutions across more than 18 Indian cities.",
  founded: 2013,

  // Two distinct contact paths:
  //   enquiries → clients who want us to work for them (Head of Projects)
  //   careers   → people who want to work for us (Head of HR)
  emails: {
    enquiries: "prakhar@thelaundrybag.co.in",
    careers: "hr@thelaundrybag.co.in",
    // Legacy aliases (kept so older references keep resolving correctly).
    contact: "prakhar@thelaundrybag.co.in",
    hr: "hr@thelaundrybag.co.in",
  },
  phone: "+91 80859 90015",
  phoneDisplay: "(+91) 8085990015",
  phoneRaw: "8085990015",
  hours: "9:00 AM – 9:00 PM",

  // Who to talk to, by intent.
  contacts: {
    enquiries: {
      role: "Head of Projects",
      blurb: "For hotels, hospitals and businesses that want to work with us.",
      email: "prakhar@thelaundrybag.co.in",
      phoneDisplay: "(+91) 8085990015",
      phoneRaw: "8085990015",
    },
    careers: {
      role: "Head of HR",
      blurb: "For people looking to join our organisation.",
      email: "hr@thelaundrybag.co.in",
    },
  },

  address: {
    street: "Kusum Complex, Near Jain Mandir, T.V. Tower Road, Shankar Nagar",
    city: "Raipur",
    region: "Chhattisgarh",
    postalCode: "492007",
    country: "India",
    countryCode: "IN",
    full: "Kusum Complex, Near Jain Mandir, T.V. Tower Road, Shankar Nagar, Raipur, Chhattisgarh, India - 492007",
    mapsHref:
      "https://www.google.com/maps/search/?api=1&query=The+Laundry+Bag+Shankar+Nagar+TV+Tower+Road+Raipur",
    mapsEmbedHref:
      "https://maps.google.com/maps?q=21.24957,81.6602156&hl=en&z=14&ie=UTF8&iwloc=&output=embed",
    geo: { lat: 21.24957, lng: 81.6602156 },
  },

  // 18-city footprint (Raipur and Naya Raipur counted as one metro).
  // Keep in sync with the operations map (src/data/mapMarkers.ts).
  cities: [
    "Raipur",
    "Durg",
    "Nagpur",
    "Goa",
    "Mumbai",
    "Pune",
    "Chennai",
    "Kolkata",
    "Hyderabad",
    "Bengaluru",
    "Ahmedabad",
    "Jaipur",
    "Lucknow",
    "Chandigarh",
    "Dehradun",
    "Bodhgaya",
    "Ranchi",
    "Tirupati",
  ],

  socials: {
    facebook: "https://www.facebook.com/inthelaundrybag/",
    twitter: "https://twitter.com/inthelaundrybag",
    instagram: "https://www.instagram.com/inthelaundrybag/",
    linkedin: "https://www.linkedin.com/company/the-laundry-bag/",
  },

  website: "https://www.thelaundrybag.co.in",

  press: [
    {
      title: "YourStory · The Laundry Bag",
      href: "https://yourstory.com/mystory/baff4ffd31-the-laundry-bag",
      source: "YourStory",
    },
    {
      title: "Startup Buzz · This Pune startup is redefining laundry services",
      href: "https://www.startup-buzz.com/pune-startup-redefining-laundry-services/",
      source: "Startup Buzz",
    },
    {
      title: "Letsmarkup · The man behind The Laundry Bag",
      href: "http://letsmarkup.com/the-man-behind-the-laundry-bag",
      source: "Letsmarkup",
    },
  ],
};

// Responsive image descriptor consumed by <ResponsiveImage>. `base` + `widths`
// resolve to /public/images/press/<base>-<w>.{webp,jpg} (generated by
// scripts/process-press-media.mjs). `width`/`height` are the intrinsic size of
// the largest variant, set to reserve space and avoid layout shift.
export type PressImage = {
  base: string;
  widths: number[];
  width: number;
  height: number;
  alt: string;
};

// ----- PRESS COVERAGE --------------------------------------------------------
// Headline coverage: the MoU between The Laundry Bag and the Chhattisgarh State
// Skill Development Authority (CSSDA), signed at the "Chhattisgarh Skill Tech"
// event in Raipur in the presence of Hon'ble CM Shri Vishnu Deo Sai. Details
// verified against The Hitavada (Raipur, 25 Dec 2025, p.7) and Patrika.
export const pressFeature = {
  kicker: "Government MoU · Skill development",
  outlet: "The Hitavada",
  edition: "Raipur · 25 December 2025",
  title: "CSSDA ties up with The Laundry Bag to boost job-oriented training",
  dek: "A government partnership to professionalise India\u2019s organised laundry workforce \u2014 turning everyday laundry skills into certified, job-ready training for hospitality, healthcare and commercial linen.",
  facts: [
    { label: "Signed with", value: "Chhattisgarh State Skill Development Authority" },
    { label: "Programme", value: "Laundry Operations \u2013 Skill Development" },
    { label: "Signed at", value: "Chhattisgarh Skill Tech, Raipur" },
    { label: "Presided by", value: "Hon\u2019ble CM Shri Vishnu Deo Sai" },
  ],
  image: {
    base: "/images/press/mou-cm-hero",
    widths: [640, 1024, 1600],
    width: 1600,
    height: 900,
    alt: "Founder Shourya Jain and partner Neeti Jain exchange the MoU with the Chhattisgarh State Skill Development Authority in the presence of Hon\u2019ble Chief Minister Shri Vishnu Deo Sai at Chhattisgarh Skill Tech, Raipur.",
  } as PressImage,
  video: {
    mp4: "/media/mou-cm.mp4",
    webm: "/media/mou-cm.webm",
    poster: "/images/press/mou-cm-hero-1024.jpg",
    durationSec: 43,
    captions: [
      { src: "/media/mou-cm.en.vtt", srclang: "en", label: "English" },
      { src: "/media/mou-cm.hi.vtt", srclang: "hi", label: "हिन्दी" },
    ],
    summary:
      "At the Chhattisgarh Skill Tech event in Raipur, the MoU between The Laundry Bag and the state\u2019s skill-development department is announced and exchanged on stage in the presence of Hon\u2019ble Chief Minister Shri Vishnu Deo Sai and the Hon\u2019ble Industry Minister.",
  },
};

// Newspaper clippings, shown full-frame in a zoom lightbox so the text reads.
export const pressClippings: { outlet: string; edition: string; title: string; image: PressImage }[] = [
  {
    outlet: "The Hitavada",
    edition: "Raipur City Line \u00B7 25 Dec 2025 \u00B7 Page 7",
    title: "CSSDA ties up with The Laundry Bag to boost job-oriented training",
    image: {
      base: "/images/press/clipping-hitavada",
      widths: [1000, 2000],
      width: 2000,
      height: 1566,
      alt: "The Hitavada article: \u2018CSSDA ties up with The Laundry Bag to boost job-oriented training\u2019, Raipur, 25 December 2025.",
    },
  },
  {
    outlet: "Patrika",
    edition: "Raipur \u00B7 December 2025",
    title: "Chhattisgarh Skill Tech \u2014 skill-integrated industrial development",
    image: {
      base: "/images/press/clipping-patrika",
      widths: [1000, 2000],
      width: 2000,
      height: 2667,
      alt: "Patrika (Hindi) coverage of the Chhattisgarh Skill Tech event in Raipur where the MoU was signed.",
    },
  },
];

// Founder appearances / recognition gallery (real photographs).
export const pressGallery: { caption: string; image: PressImage }[] = [
  {
    caption: "Founder Shourya Jain and partner Neeti Jain receive the MoU from Hon\u2019ble CM Shri Vishnu Deo Sai",
    image: {
      base: "/images/press/mou-cm-closeup",
      widths: [400, 800, 1200],
      width: 1200,
      height: 900,
      alt: "Hon\u2019ble Chief Minister Shri Vishnu Deo Sai with The Laundry Bag founder Shourya Jain and partner Neeti Jain during the MoU exchange.",
    },
  },
  {
    caption: "On stage with senior CSSDA officials at Chhattisgarh Skill Tech, Raipur",
    image: {
      base: "/images/press/mou-cm-group",
      widths: [400, 800, 1200],
      width: 1200,
      height: 900,
      alt: "The Laundry Bag team with the Hon\u2019ble Chief Minister and senior CSSDA officials at the MoU exchange ceremony in Raipur.",
    },
  },
];

// Standout milestone: founder Shourya Jain met the late Shri Ratan Tata while
// inaugurating The Laundry Bag's dedicated laundry unit at Tata Medical Center,
// Kolkata, a newly onboarded healthcare site. Copy is written in the brand's
// own voice; no quotes are attributed to Shri Ratan Tata.
export const ratanTata = {
  eyebrow: "A milestone we will always cherish",
  kicker: "Tata Medical Center · Kolkata",
  title: "An honour: meeting the late Shri Ratan Tata",
  lead: "When The Laundry Bag commissioned its dedicated in-house laundry unit at Tata Medical Center, Kolkata, founder Shourya Jain travelled to inaugurate the new facility, and had the rare privilege of meeting the late Shri Ratan Tata.",
  body: [
    "Tata Medical Center is among India\u2019s most respected cancer hospitals, where linen hygiene sits at the very heart of safe patient care. Standing up a hospital-grade laundry on this campus was a defining moment in our healthcare journey \u2014 proof that The Laundry Bag\u2019s never-mix, infection-aware processes belong in the country\u2019s finest institutions.",
    "Meeting Shri Ratan Tata that day turned an already special occasion into one our team will never forget \u2014 a quiet, lasting reminder of the values of trust, humility and uncompromising quality that continue to guide everything we do.",
  ],
  pullQuote:
    "A reminder that in healthcare, hygiene is never a detail \u2014 it is a duty.",
  facts: [
    { label: "Where", value: "Tata Medical Center, Kolkata" },
    { label: "Occasion", value: "Inauguration of the new laundry unit" },
    { label: "Sector", value: "Healthcare linen & hygiene" },
  ],
  image: {
    base: "/images/press/shourya-ratan-tata",
    widths: [400, 800, 1200],
    width: 1200,
    height: 900,
    alt: "The Laundry Bag founder Shourya Jain with the late Shri Ratan Tata at Tata Medical Center, Kolkata, during the inauguration of the hospital\u2019s new laundry unit.",
  } as PressImage,
};

// "As featured in", online press features. Links are real and verified.
export const pressFeatures = [
  {
    title: "The story behind The Laundry Bag",
    outlet: "YourStory",
    summary:
      "How The Laundry Bag set out to organise India's unorganised laundry sector with a hygienic, never-mix laundromat model.",
    href: "https://yourstory.com/mystory/baff4ffd31-the-laundry-bag",
  },
  {
    title: "Redefining laundry services",
    outlet: "Startup Buzz",
    summary:
      "A feature on the founding idea and the build-own-operate model powering laundry for campuses, hotels and hospitals.",
    href: "https://www.startup-buzz.com/pune-startup-redefining-laundry-services/",
  },
  {
    title: "The man behind The Laundry Bag",
    outlet: "Letsmarkup",
    summary:
      "Founder Shourya Jain on building one of India's leading laundry networks out of Raipur, Chhattisgarh.",
    href: "http://letsmarkup.com/the-man-behind-the-laundry-bag",
  },
];

// PRIMARY, navigation. Grouped for the new mega/standard nav.
export const navLinks = [
  { to: "/", label: "Home" },
  { to: "/about", label: "Our Journey" },
  { to: "/our-team", label: "Our Team" },
  { to: "/locations", label: "Locations" },
  { to: "/press", label: "Press" },
  { to: "/faq", label: "FAQ" },
  { to: "/contact", label: "Contact" },
];

export const homeServices = [
  {
    title: "Equipment Sales",
    description:
      "We study your existing linen flow, volumes and costs, then design the most efficient laundry setup for your property.",
    icon: "hotel",
    accent: "blue" as const,
    href: "/contact",
  },
  {
    title: "Build Own Operate",
    description:
      "We fine-tune your current operation, upgrading processes, equipment and standards to cut costs and lift quality.",
    icon: "shield",
    accent: "grey" as const,
    href: "/contact",
  },
  {
    title: "Outsourcing",
    description:
      "We take laundry off your plate entirely, running it on-premise, off-site or on a managed rental model sized to your occupancy.",
    icon: "factory",
    accent: "brand" as const,
    href: "/contact",
  },
];

export const businessServices = [
  {
    title: "Hotel Laundry",
    description:
      "Having served hotel chains of all sizes, The Laundry Bag handles laundry for properties from Grand Hyatt and Taj Exotica to JW Marriott, Hilton and Novotel. Our approach is flexible, install equipment on-site or process at our facility, handle rental linen or wash what you already own. With high-end finishing equipment and high-efficiency machines, we deliver a sustainable, affordable and responsive solution for hotels.",
  },
  {
    title: "Hospital Laundry",
    description:
      "From large medical centres like Tata Medical Center and Balco Medical Center to district hospitals, we manage hygienic, infection-safe linen processing, on-premise to maximise responsiveness or off-site to free up space. We're equipped to handle both your linen contract and patient personal laundry with the same care and attention to detail.",
  },
  {
    title: "Resorts & Premium Hospitality",
    description:
      "For resorts and luxury retreats such as Grand Hyatt Goa and Taj Exotica Goa, we deliver consistent, five-star linen, spa and F&B laundry, meeting the exacting standards your guests expect, every single day.",
  },
  {
    title: "Linen Rental & Management",
    description:
      "Save your capital on linen. We supply, launder, track and replace sheets, towels, robes and uniforms on a flexible rental model sized to your occupancy, you order, we handle the rest.",
  },
];

export const whoWeServe = [
  {
    title: "Luxury Hotels & Resorts",
    description:
      "From Grand Hyatt and Taj Exotica in Goa to JW Marriott Chandigarh, Hilton Mumbai, Novotel Chennai and Hyatt properties across India, we manage guest linen, F&B and uniform laundry to five-star standards.",
  },
  {
    title: "Hospitals & Medical Centres",
    description:
      "Tata Medical Center Kolkata, Balco Medical Center Naya Raipur, Lata Mangeshkar Hospital Nagpur, DKS Hospital Raipur, SIMS Hospital Durg and Tata Trust hospitals in Ranchi & Tirupati trust us with hygienic, infection-safe linen processing.",
  },
  {
    title: "Linen Rental & Management",
    description:
      "We supply, launder and replace sheets, towels, robes and uniforms on a flexible rental model, so hotels and hospitals save on capital, storage and replacement costs.",
  },
  {
    title: "Enterprises & Institutions",
    description:
      "Corporate campuses, universities, clubs and government establishments rely on us for managed laundry, uniform and linen programmes on a built-own-operate basis.",
  },
];

export const howItWorks = [
  {
    step: "Step 1",
    title: "Assessment",
    text: "We analyse your existing linen requirements, volumes and current operational model.",
    icon: "users",
  },
  {
    step: "Step 2",
    title: "Solution design",
    text: "We design the right model for you, on-premise, off-site or linen rental, with clear costing.",
    icon: "factory",
  },
  {
    step: "Step 3",
    title: "Transition",
    text: "We begin taking over your laundry operations with a structured, low-disruption handover plan.",
    icon: "washer",
  },
  {
    step: "Step 4",
    title: "Installation",
    text: "We install equipment, streamline SOPs and complete the operations takeover and handover.",
    icon: "check",
  },
];

export const operationalModels = [
  {
    title: "On-Premise Laundry Units",
    description:
      "The Laundry Bag™ sets up and operates fully-managed laundry facilities inside your premises, customised to your operation and fitted with best-in-class equipment, the model we run for hotels and hospitals such as Hyatt Raipur and DKS Hospital, Raipur.",
  },
  {
    title: "Central Processing Units",
    description:
      "Our central processing unit in Raipur (Chhattisgarh) is equipped with state-of-the-art machinery for clients who prefer to outsource their daily laundry. A network of well-managed logistics channels keeps service consistent and on-time across the cities we serve.",
  },
  {
    title: "Linen Rental & Management",
    description:
      "Beyond cleaning, we own and manage your linen, supplying, laundering and replacing hotel and hospital linen on a flexible rental model that frees up your capital, storage and replacement budgets.",
  },
];

export const whyChooseUs = [
  {
    title: "Zero Capex",
    description:
      "We offer models where the entire capital expenditure on equipment is in our scope.",
    icon: "leaf",
  },
  {
    title: "Cost-Effective",
    description: "We offer huge operational savings on a year on year basis.",
    icon: "tag",
  },
  {
    title: "Best in Class Equipment",
    description: "We offer best in-class imported equipment from Girbau.",
    icon: "spark",
  },
  {
    title: "Quality",
    description:
      "We use the best in-class chemicals & enzymes which enhance linen quality & life.",
    icon: "shield",
  },
  {
    title: "Standardisation",
    description: "We have standard processes which help to optimise operations.",
    icon: "truck",
  },
  {
    title: "Sustainability",
    description:
      "We use the lowest per kg water, 100% electric fired equipment, free from Boiler.",
    icon: "star",
  },
];

export const counters = [
  { value: "5,00,000+", label: "Laundry Done" },
  { value: "15", label: "Washing Machines Works" },
  { value: "50,000+", label: "Dry Cleaned Items" },
  { value: "3,500", label: "Happy Customers" },
];

export const testimonials = [
  {
    name: "Front Office, Luxury Hotel · Goa",
    quote:
      "Linen quality and finishing are consistent across thousands of pieces a day. The on-premise team feels like part of our own operation.",
  },
  {
    name: "Sudhanshu Dixit",
    quote: "Their service is so good. I like their work. The staff is so excellent.",
  },
  {
    name: "Facility Manager · Hospital",
    quote:
      "Hygienic, infection-safe processing and dependable stock levels in every ward. Reliability we can genuinely count on.",
  },
  {
    name: "Jyoti",
    quote:
      "Their services are amazing, you all will be satisfied with them. Highly recommended.",
  },
  {
    name: "Operations Lead · Resort",
    quote:
      "Five-star finishing, never-mixed linen and a responsive team. Exactly what a premium property needs from a laundry partner.",
  },
];

export const commercialFeatures = [
  {
    title: "Linen & Laundry",
    description:
      "We collect, sort, pre-treat, wash, dry and finish your linen to specification, guest-room linen, towels, F&B, uniforms and patient linen, returned on a managed schedule.",
    image: "/images/img_02.jpg",
  },
  {
    title: "Dry Cleaning Services",
    description:
      "We use Lagoon Advanced Care for Dry-Clean-Only tags. Fast, easy and green cleaning solutions for professional textile care.",
    image: "/images/img_03.jpg",
  },
  {
    title: "Upholstery & Carpet Cleaning",
    description:
      "To keep your investment safe, we recommend professional deep cleaning your carpet every few months, and we are best at doing that.",
    image: "/images/img_04.jpg",
  },
];

export const commercialSubFeatures = [
  {
    title: "Sheets & Towels",
    description:
      "Our linen program covers a range of products appropriate for use in businesses of all types and sizes. From the bedding for a 100-bed hospital to the hand towels at a local coffee shop.",
  },
  {
    title: "Janitorial Supplies",
    description:
      "We offer a flat weekly rental price for items which includes our sustainable laundering and delivery service. We are also available to launder items you may already own.",
  },
  {
    title: "Entryway and Floor Mats",
    description:
      "We offer standard or customizable floor and entryway mats for a professional, clean appearance at your business that also increase safety and comfort for staff and customers.",
  },
  {
    title: "Linen Rentals",
    description:
      "Save investments on all the linen you purchase for your business, just order from us according to your occupancy and we'll handle the rest.",
  },
  {
    title: "All Under One Roof",
    description:
      "From Sofa, Carpets to Upholstery, we have it all under control for you.",
  },
];

export const locations = [
  {
    city: "Raipur",
    state: "Chhattisgarh",
    role: "Headquarters · Central Processing Unit",
    image: "/images/raipur-location.png",
    description:
      "Our headquarters and central processing unit at Shankar Nagar, equipped with state-of-the-art machinery. From here we run fully-managed on-premise units and linen programmes for Hyatt Raipur, DKS Hospital and Balco Medical Center, Naya Raipur, supported by a managed logistics network.",
  },
  {
    city: "Goa",
    state: "Goa",
    role: "Luxury hospitality",
    image: "/images/goa-location-new.png",
    description:
      "We manage linen for Goa's marquee hospitality, including Grand Hyatt Goa and Taj Exotica Goa, delivering five-star washing, finishing and linen-rental programmes for resorts and the guests they host.",
  },
  {
    city: "Across India",
    state: "18 cities",
    role: "Hotels & Hospitals",
    image: "/images/pune-location.png",
    description:
      "From Hilton Mumbai, JW Marriott Chandigarh and Novotel Chennai to Tata Medical Center Kolkata and Lata Mangeshkar Hospital Nagpur, our teams run laundry and linen programmes for leading hotels and hospitals nationwide.",
  },
];

export const extraCities = [
  { city: "Mumbai", note: "Linen & laundry for Hilton, Mumbai." },
  { city: "Chennai", note: "Hyatt Regency and Novotel, Chennai." },
  { city: "Kolkata", note: "Hyatt Regency and Tata Medical Center, Kolkata." },
  { city: "Hyderabad", note: "Hyatt, Hyderabad." },
  { city: "Bengaluru", note: "Hyatt Centric, Bangalore." },
  { city: "Ahmedabad", note: "Hyatt Regency and Hyatt, Vastrapur." },
  { city: "Jaipur", note: "Hyatt Place, Jaipur." },
  { city: "Lucknow", note: "Hyatt Regency, Lucknow." },
  { city: "Dehradun", note: "Hyatt Regency, Dehradun." },
  { city: "Chandigarh", note: "JW Marriott, Chandigarh." },
  { city: "Bodhgaya", note: "Hyatt Place, Bodhgaya." },
  { city: "Pune", note: "Hyatt, Pune." },
  { city: "Nagpur", note: "Lata Mangeshkar Hospital, Nagpur." },
  { city: "Durg", note: "SIMS Hospital, Durg." },
  { city: "Ranchi & Tirupati", note: "Tata Trust supported hospitals." },
];

export const faqs = [
  {
    category: "Working with hotels & hospitals",
    items: [
      {
        q: "What kinds of businesses does The Laundry Bag work with?",
        a: "We are a B2B commercial laundry partner. We run laundry and linen programmes for luxury hotels, resorts, hospitals, medical centres, corporate campuses, universities and other institutions across India.",
      },
      {
        q: "Can you set up and run a laundry unit inside our property?",
        a: "Yes. Our most popular model is a fully-managed on-premise laundry: we install best-in-class equipment inside your facility, hire and manage the team, and operate it to your standards on a Built-Own-Operate basis. It maximises responsiveness and frees up your team.",
      },
      {
        q: "What if we don't have space for an on-site unit?",
        a: "Then we process your linen off-site at our nearest central processing unit and manage collection and return on a fixed schedule, backed by a managed logistics network so stock levels never run short.",
      },
      {
        q: "How do you ensure hygienic, infection-safe processing for hospitals?",
        a: "Healthcare linen is processed on standardised, temperature-controlled cycles with segregated soiled and clean flows, validated detergents and disinfection, designed to meet the hygiene expectations of hospitals and medical centres.",
      },
      {
        q: "What linen and items do you handle?",
        a: "Guest-room linen, towels, bathrobes, F&B and banquet linen, spa linen, staff uniforms, patient linen, theatre linen, floor and entryway mats, upholstery and carpets, sheets to scrubs.",
      },
    ],
  },
  {
    category: "Linen rental & management",
    items: [
      {
        q: "How does linen rental work?",
        a: "We own the linen and you pay a flat, predictable rental that includes laundering, finishing, delivery and replacement. You free up capital, storage and replacement budgets, and only ever pay for what your occupancy needs.",
      },
      {
        q: "Can you also launder linen we already own?",
        a: "Absolutely. We are happy to wash and finish the linen you already own, supply rental linen, or run a blend of both, whichever is most cost-effective for your operation.",
      },
      {
        q: "What happens to worn-out or stained linen?",
        a: "Every piece is tracked through its lifecycle. Linen that no longer meets standard is pulled from rotation and replaced as part of the managed programme, so guests and patients only ever see fresh, presentable linen.",
      },
    ],
  },
  {
    category: "Operations, quality & getting started",
    items: [
      {
        q: "What is your turnaround time?",
        a: "Soiled and stained linen is typically processed and finished within 24 hours. For on-premise units, turnaround is continuous and matched to your daily volumes.",
      },
      {
        q: "Do you mix our linen with other clients'?",
        a: "Never. Our founding USP is that we do not mix one client's linen with anyone else's, every client's stock is processed, tracked and stored separately.",
      },
      {
        q: "What equipment and detergents do you use?",
        a: "Our laundries are engineered with Girbau, the Spanish engineering leader trusted by the world's top operations, and we use Lagoon Advanced Care for delicate and dry-clean-only items. Our process is PERC-free, uses all-natural detergents and saves roughly 5,000 litres of water a day. The Laundry Bag is an ISO-certified company.",
      },
      {
        q: "Which cities do you operate in?",
        a: "We are headquartered in Raipur, Chhattisgarh and run programmes for hotels and hospitals across 18 cities including Goa, Mumbai, Pune, Chennai, Kolkata, Hyderabad, Bengaluru, Ahmedabad, Jaipur, Lucknow, Chandigarh, Dehradun, Nagpur, Durg, Bodhgaya, Ranchi and Tirupati.",
      },
      {
        q: "How do we get started or request a proposal?",
        a: "Call us on (+91) 8085990015 or send an enquiry from the Contact page. We'll assess your linen, volumes and space, then propose the right model, on-premise, off-site or linen rental, with clear pricing.",
      },
    ],
  },
  {
    category: "About the founder",
    items: [
      {
        q: "Who is Shourya Jain?",
        a: "Shourya Jain is a Raipur, Chhattisgarh based entrepreneur and the founder of The Laundry Bag, India's leading commercial laundry, dry-cleaning and linen-management brand for hotels, hospitals and institutions. He is also the third-generation real estate partner at Shourya Infraventure, his family's Raipur infrastructure firm established in 1958.",
      },
      {
        q: "Who founded The Laundry Bag?",
        a: "The Laundry Bag was founded by Shourya Jain, a Raipur based entrepreneur, and has grown since 2013 into a Built-Own-Operate laundry and linen partner serving luxury hotels, resorts and hospitals across more than 18 Indian cities from its Raipur headquarters.",
      },
      {
        q: "Is the founder of The Laundry Bag the same Shourya Jain from Shourya Infraventure?",
        a: "Yes. Shourya Jain of The Laundry Bag is the same Raipur entrepreneur who is the third-generation real estate partner at Shourya Infraventure, the Jain family infrastructure firm established in 1958. He runs both the laundry business and the family real estate business from Raipur, Chhattisgarh.",
      },
    ],
  },
];

// ----- RESEARCHED ------------------------------------------------------------
// Sourced from public profiles (LinkedIn, JustDial, Play Store, press) and
// cross-referenced with the owner's known details. Review before publishing.

// Founder / leadership (LinkedIn, Startup Buzz, Letsmarkup).
export const founders = [
  {
    name: "Shourya Jain",
    role: "Founder",
    bio: "Founder of The Laundry Bag™. Based in Raipur, Chhattisgarh, Shourya leads the company's mission to organise India's unorganised laundry sector, building one of India's leading laundry networks and a Built-Own-Operate linen platform for hotels, hospitals and enterprises across the country. He is also the third-generation real estate partner at Shourya Infraventure, his family's Raipur infrastructure firm established in 1958.",
    href: "https://www.linkedin.com/in/shourya-jain-raipur",
    image: "/images/team/shourya-jain.jpg",
  },
];

/** Head Office team — edit names, roles and bios here; photos go in /public/images/team/ */
export type TeamMember = {
  id: string;
  name: string;
  role: string;
  department: string;
  bio: string;
  email?: string;
  image?: string;
  linkedIn?: string;
};

export const headOfficeTeam = {
  location: "Raipur, Chhattisgarh",
  intro:
    "The Laundry Bag™ is built on core values of integrity and honesty. We have a very strong and experienced team of young and talented individuals who handle their respective vertical with the customers expectations in mind.",
  members: [
    {
      id: "shourya-jain",
      name: "Shourya Jain",
      role: "Investor & Founder",
      department: "Leadership",
      bio: "Founder and Investor in The Laundry Bag™. Key responsible for strategy, growth plans, vision allignment, backward-forward integration to suit the requirements of evolving markets and requirements.",
      image: "/images/team/shourya-jain.jpg",
      linkedIn: "https://www.linkedin.com/in/shourya-jain-raipur",
    },
    {
      id: "prakhar-singh",
      name: "Prakhar Singh",
      role: "Head of Projects",
      department: "Projects",
      bio: "Almost 10 years into the company, heads new business development, project design, pre operations and commissioning of all projects across India.",
    },
    {
      id: "nirmal-kumar",
      name: "Nirmal Kumar",
      role: "Deputy Head of Projects",
      department: "Projects",
      bio: "Almost 9 years into the company, oversees new installations, low sides, equipment and technology innovation along side product development and management.",
    },
    {
      id: "deep-titermare",
      name: "Deep Titermare",
      role: "Head of Operations",
      department: "Operations",
      bio: "Leads day-to-day operations across client accounts and on-site teams, ensuring processing quality, turnaround and service delivery across the network.",
    },
    {
      id: "akash-singh-baghel",
      name: "Akash Singh Baghel",
      role: "Deputy Head of Operations",
      department: "Operations",
      bio: "Supports day-to-day operations across client accounts, keeping processing quality, turnaround and on-site teams on track.",
    },
    {
      id: "vivek-devnani",
      name: "Vivek Devnani",
      role: "Head of Finance",
      department: "Finance",
      bio: "Leads finance, billing and budgeting, keeping the company's commercial and financial planning on a firm footing.",
    },
    {
      id: "vishwashree-pandey",
      name: "Vishwashree Pandey",
      role: "Head of HR",
      department: "People",
      bio: "Leads recruitment, training and people operations, building the teams that run our units across India.",
    },
    {
      id: "naman-kunhappan",
      name: "Naman Kunhappan",
      role: "Head of AI & Technology",
      department: "Technology",
      bio: "Builds the software, data and AI tools that help us track quality, turnaround and performance across the network.",
    },
    {
      id: "gaurav-joshi",
      name: "Gaurav Joshi",
      role: "Head of Engineering",
      department: "Engineering",
      bio: "Leads engineering and systems work that keeps our plants and technology running, from infrastructure to process improvements.",
    },
  ] satisfies TeamMember[],
};

// Company facts for the "Our Story" / about section.
export const companyFacts = [
  { label: "Founded", value: "2013" },
  { label: "Headquarters", value: "Raipur, Chhattisgarh" },
  { label: "Focus", value: "Commercial Laundry & Linen" },
  { label: "Presence", value: "India · 18 cities" },
];

// Brand story timeline (compiled from press + the legacy site).
export type TimelineEntry = {
  year: string;
  title: string;
  text?: string;
  textBold?: boolean;
};

export const timeline = [
  {
    year: "2014",
    title: "The Laundry Bag™ sets up its first on campus laundromatte at Symbiosis, Pune",
    text: "",
  },
  {
    year: "2015",
    title:
      "The Laundry Bag™ starts its On-Demand Laundry & Delicate Garment Care facility in Raipur with a focus to cater to the emerging retail market",
    text: "",
  },
  {
    year: "2016",
    title: "The Laundry Bag™ starts commercial laundry operations in Delhi on a hub and spoke model.",
    text: "",
  },
  {
    year: "2017",
    title: "The Laundry Bag™ sets up its first Build own operate Laundry for a Hotel",
    text: "",
  },
  {
    year: "2018",
    title: "The Laundry Bag™ scales up operations by starting 5 new Hotel & Hospital projects on Build - Own - Operate Model",
    text: "",
  },
  {
    year: "2019",
    title: "The Laundry Bag™ signs a major deal with Girbau for purchase and distribution of Laundry Equipment",
    text: "",
  },
  {
    year: "2020",
    title: "The Laundry Bag™ begins consolidation of operations during covid",
    text: "",
  },
  {
    year: "2021",
    title: "The Laundry Bag™ starts Optimisation models to help reduce operating costs for major Hotel Chains across India",
    text: "",
  },
  {
    year: "2022 - 2025",
    title: "The Laundry Bag™ sets up multiple units across India on Build - Own - Operate & Hy-brid Models to become a leader in its segment with 30+ projects in 18 cities",
    text: "",
  },
  {
    year: "2026",
    title: "The Laundry Bag™ is setting up a full scale linen manufacturing unit & a 3 MW solar power plant to further scale operations through various innovative models while aiming at generating 100% of the consumed power across India through sustainable means.",
    text: "",
  },
];

// Differentiators / USPs (legacy + Play Store copy).
export const usps = [
  {
    title: "We never mix your linen",
    description:
      "Unlike other operators, WE DO NOT MIX one client's linen with another's. Every property's stock is processed, tracked and stored separately.",
    icon: "shield",
  },
  {
    title: "24-hour finish",
    description:
      "Soiled or stained linen is processed and finished in a clean, hygienic environment, typically within 24 hours.",
    icon: "clock",
  },
  {
    title: "On-premise or off-site",
    description:
      "Run a fully-managed laundry inside your property, or process at our central facility, whichever fits your operation and space.",
    icon: "factory",
  },
  {
    title: "PERC-free & eco-friendly",
    description:
      "We wash in all-natural detergents and our dry-cleaning process is PERC-free, saving roughly 5,000 litres of water a day.",
    icon: "leaf",
  },
];

// "Why TLB", quantitative proof points, animated as a stat band.
export const whyTlbStats = [
  { value: "12+", label: "Years of expertise", icon: "clock" },
  { value: "500+", label: "Skilled employees", icon: "users" },
  { value: "18", label: "Cities", icon: "pin" },
  { value: "30+", label: "Operational units", icon: "factory" },
];

export const whyTlbStatGroups = [
  { badge: "Network & scale", stats: whyTlbStats.slice(2, 4) },
  { badge: "People & experience", stats: whyTlbStats.slice(0, 2) },
];

// "Why TLB", qualitative trust tiles shown alongside the stat band.
export const whyTlbFeatures = [
  {
    badge: "Global technology partner",
    title: "Engineered with Girbau, Spain",
    description:
      "Our laundries run on Girbau, the Spanish engineering leader trusted by the world's top corporations. The same technology behind global operations now powers yours.",
    icon: "spark",
  },
  {
    badge: "Third-generation business",
    title: "Equity backed. Built on Values.",
    description:
      "A largely equity-funded, third-generation enterprise, financially solid and built for the long term. The partner you choose today is the partner you keep.",
    icon: "shield",
  },
];

// Client / partner directory grouped by sector (legacy + research).
export const clientGroups = [
  {
    sector: "Hospitality",
    items: [
      "Grand Hyatt, Goa",
      "Taj Exotica, Goa",
      "JW Marriott, Chandigarh",
      "Hilton, Mumbai",
      "Novotel, Chennai",
      "Five Lotus, Raitum",
      "Hyatt Regency · Chennai, Kolkata, Lucknow, Ahmedabad, Dehradun",
      "Hyatt Centric, Bangalore",
      "Hyatt Place · Jaipur, Bodhgaya",
      "Hyatt · Hyderabad, Pune, Raipur, Vastrapur",
    ],
  },
  {
    sector: "Healthcare",
    items: [
      "Tata Medical Center, Kolkata",
      "Tata Trust Hospitals · Ranchi & Tirupati",
      "Balco Medical Center, Naya Raipur",
      "Lata Mangeshkar Hospital, Nagpur",
      "DKS Hospital, Raipur",
      "SIMS Hospital, Durg",
    ],
  },
];

// Brand-level logo wall for the home-page & commercial marquees. `logo` points
// to an SVG in /public/images/clients. If a logo file is missing, the marquee
// gracefully falls back to a styled wordmark of `name`.
export const clientLogos = [
  { name: "Taj Hotels", logo: "/images/clients/taj.svg" },
  { name: "Marriott", logo: "/images/clients/marriott.svg" },
  { name: "Hyatt", logo: "/images/clients/hyatt.svg" },
  { name: "Hilton", logo: "/images/clients/hilton.svg" },
  { name: "Novotel", logo: "/images/clients/novotel.svg" },
  {
    name: "Tata Medical Center",
    logo: "/images/clients/tata-medical-center.png",
  },
  { name: "Balco Medical Centre", logo: "/images/clients/balco.png" },
  { name: "SIMS Hospital", logo: "/images/clients/sims-hospital.webp" },
];

// Flat name list (kept for back-compat / SEO use).
export const featuredClients = [
  "Grand Hyatt, Goa",
  "Taj Exotica, Goa",
  "JW Marriott, Chandigarh",
  "Hilton, Mumbai",
  "Novotel, Chennai",
  "Hyatt Regency, Kolkata",
  "Hyatt Regency, Chennai",
  "Hyatt Regency, Lucknow",
  "Hyatt Regency, Ahmedabad",
  "Hyatt Regency, Dehradun",
  "Hyatt Centric, Bangalore",
  "Hyatt Place, Jaipur",
  "Hyatt Place, Bodhgaya",
  "Hyatt, Hyderabad",
  "Hyatt, Pune",
  "Hyatt, Raipur",
  "Hyatt, Vastrapur",
  "Five Lotus, Raitum",
  "Tata Medical Center, Kolkata",
  "Tata Trust Hospitals · Ranchi & Tirupati",
  "Balco Medical Center, Naya Raipur",
  "Lata Mangeshkar Hospital, Nagpur",
  "DKS Hospital, Raipur",
  "SIMS Hospital, Durg",
];

// SEO, non-visible keyword list (meta tags + JSON-LD).
// B2B-focused superset: brand, geography, commercial/hotel/hospital laundry
// and the sole-founder (Shourya Jain) permutations Googlebot already indexes.
export const seoKeywords = [
  // brand / business
  "laundry",
  "laundry bag",
  "the laundry bag",
  "The Laundry Bag",
  "thelaundrybag",
  "the laundrybag",
  "laundry basket",
  "TLB",
  "TLB Raipur",
  "TLB laundry",
  "TLB India",
  "best laundry",
  "best laundry service",
  "best laundry in India",
  "best laundry in Raipur",
  "best dry cleaning Raipur",
  "best dry cleaning India",
  // geography
  "India",
  "Raipur",
  "Chhattisgarh",
  "Raipur Chhattisgarh",
  "Raipur India",
  "Chhattisgarh India",
  "Pune",
  "Goa",
  "Mumbai",
  "Chennai",
  "Kolkata",
  "Hyderabad",
  "Bengaluru",
  "Ahmedabad",
  "Jaipur",
  "Lucknow",
  "Chandigarh",
  "Dehradun",
  "Nagpur",
  "Durg",
  // service permutations
  "laundry service India",
  "laundry service Raipur",
  "laundry service Chhattisgarh",
  "laundry service in India",
  "laundry service in Raipur",
  "laundry service in Chhattisgarh",
  "laundry near me",
  "laundry Raipur",
  "laundry Chhattisgarh",
  "laundry India",
  "laundry in raipur",
  "laundry in india",
  "laundry in chhattisgarh",
  "laundry in pune",
  "laundry in goa",
  "laundry in mumbai",
  "laundry in chennai",
  "laundry in kolkata",
  "laundry in hyderabad",
  "the laundry bag Raipur",
  "the laundry bag India",
  "the laundry bag Chhattisgarh",
  // tagline / positioning
  "India's Leading Laundry Service Provider",
  "leading laundry service provider India",
  "leading laundry company India",
  // commercial / specialty (B2B focus)
  "commercial laundry",
  "commercial laundry India",
  "commercial laundry in india",
  "commercial laundry Raipur",
  "commercial laundry service",
  "industrial laundry India",
  "hotel laundry service",
  "hotel laundry service India",
  "hospital laundry service",
  "hospital laundry service India",
  "luxury hotel laundry",
  "5 star hotel laundry",
  "hotel linen rental",
  "hotel linen management",
  "hospital linen management",
  "linen rental India",
  "linen management India",
  "resort laundry service",
  "on premise laundry",
  "built own operate laundry",
  "B2B laundry India",
  "institutional laundry",
  "dry cleaning",
  "dry cleaning Raipur",
  "dry cleaners Raipur",
  "dry cleaning in india",
  // founder (Shourya Jain, sole founder)
  "Shourya Jain",
  "shourya jain",
  "Shourya Jain Raipur",
  "Shourya Jain Chhattisgarh",
  "Shourya Jain India",
  "Shourya Jain TLB",
  "Shourya Jain the laundry bag",
  "Shourya Jain laundry",
  "Shourya Jain founder",
  "founder of The Laundry Bag",
  "owner of The Laundry Bag",
  "the laundry bag Shourya Jain",
  "laundry bag Shourya Jain",
  "TLB Shourya Jain",
  "Shourya Jain Raipur Chhattisgarh",
];

// Convenience aliases for back-compat.
export const commercial = commercialFeatures;
export const stats = counters;
